part1:
	g++ http_server.cpp -o http_server -lpthread -std=c++14 -lboost_system -lboost_filesystem
	g++ console.cpp -o console.cgi -lpthread
part2:
	g++ cgi_server.cpp -o cgi_server -lws2_32 -lwsock32 -std=c++14